=== zeluizgo/oprev/website.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Jose Luiz (Modem Media) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="header-info">
		<xs:annotation>
			<xs:documentation>Uma header-info representa as informações do header html de uma seção do site.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="author" type="xs:string"/>
			<xs:attribute name="keywords" type="xs:string"/>
			<xs:attribute name="description" type="xs:string"/>
			<xs:attribute name="favicon" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="header-area">
		<xs:annotation>
			<xs:documentation>A header-area corresponde a area superior da tela, no leiaute da pagina, onde ficam o menu institucional, menu de segmentos, logos e graficos.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ad-main" type="ad-mainType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>grafico principal do header da pagina</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="mini-menu" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="left-area">
		<xs:annotation>
			<xs:documentation>A left-area corresponde a area esquerda da tela, no leiaute da pagina, onde ficam o menu operacional e opcionalmente alguns destaques graficos com links, etc.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="menu" maxOccurs="2"/>
				<xs:element ref="destaque" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="footer-area" type="xs:string">
		<xs:annotation>
			<xs:documentation>A footer-area corresponde a area inferior da tela, no leiaute da pagina, onde ficam as anotacoes de Copyright e infos Institucionais,  etc.</xs:documentation>
			<xs:documentation>A footer-area corresponde a area inferior da tela, no leiaute da pagina, onde ficam as anotacoes de Copyright e infos Institucionais,  etc.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="image">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="imageType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="link">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="linkType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="text" type="inner-text"/>
	<xs:complexType name="inner-text" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="br"/>
			<xs:element name="u" type="inner-paragraph"/>
			<xs:element name="b">
				<xs:complexType mixed="true">
					<xs:complexContent mixed="true">
						<xs:extension base="inner-paragraph"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="i" type="inner-paragraph"/>
			<xs:element name="ul">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="li" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="ol">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="li" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="p" type="inner-paragraph"/>
			<xs:element ref="image"/>
			<xs:element ref="link"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="inner-paragraph">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="i" type="inner-paragraph"/>
			<xs:element name="u" type="inner-paragraph"/>
			<xs:element name="b" type="inner-paragraph"/>
			<xs:element name="ul">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="li" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="ol">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="li" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element ref="link"/>
			<xs:element ref="image"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="inner-menu">
		<xs:sequence>
			<xs:element name="menu-section" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="title"/>
						<xs:element name="menu-item" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="linkType">
										<xs:attribute name="id" type="xs:string"/>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="menu-folder" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="title"/>
									<xs:element name="menu-subitem" type="linkType" maxOccurs="unbounded"/>
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="inner-mini-menu">
		<xs:sequence>
			<xs:element name="menu-item" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="image"/>
						<xs:element name="imageOn" type="imageType" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute name="href" type="xs:string" use="required"/>
					<xs:attribute name="onclick" type="xs:string"/>
					<xs:attribute name="type" type="xs:NMTOKEN"/>
					<xs:attribute name="class" type="xs:string"/>
					<xs:attribute name="onMouseOver" type="xs:string"/>
					<xs:attribute name="onMouseOut" type="xs:string"/>
					<xs:attribute name="section" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="location" type="xs:NMTOKEN" use="required"/>
	</xs:complexType>
	<xs:element name="title">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="image"/>
				<xs:element ref="text"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="menu">
		<xs:annotation>
			<xs:documentation>Menu principal das paginas</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="inner-menu">
					<xs:attribute name="userstatus" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="logged"/>
								<xs:enumeration value="notlogged"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="mini-menu" type="inner-mini-menu"/>
	<xs:complexType name="inner-destaque">
		<xs:sequence>
			<xs:element ref="title"/>
			<xs:element ref="body"/>
			<xs:element ref="image" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="inner-body">
		<xs:sequence maxOccurs="unbounded">
			<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="text" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="body" type="inner-body"/>
	<xs:complexType name="inner-article">
		<xs:sequence>
			<xs:element ref="title"/>
			<xs:element ref="body"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="article" type="inner-article"/>
	<xs:element name="right-area">
		<xs:annotation>
			<xs:documentation>A right-area corresponde a area a direita da tela, no leiaute da pagina, onde ficam destaques graficos com links e etc.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element name="logado">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="destaque" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="nlogado">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="destaque" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="destaque">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="inner-destaque">
					<xs:attribute name="bodybgcolor" type="xs:string" use="required"/>
					<xs:attribute name="titlebgcolor" type="xs:string" use="required"/>
					<xs:attribute name="height" type="xs:integer" use="required"/>
					<xs:attribute name="width" type="xs:integer"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="center-area">
		<xs:annotation>
			<xs:documentation>A center-area corresponde a area central do leiaute da pagina</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nlogado">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="article" minOccurs="0"/>
							<xs:element ref="destaque" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="image" minOccurs="0"/>
							<xs:element ref="imageFlash" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="logado" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="destaque" maxOccurs="unbounded"/>
							<xs:element ref="teaser-box" maxOccurs="unbounded"/>
							<xs:element name="banner" type="imageType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ad-mainType">
		<xs:sequence>
			<xs:element name="bg-image" type="imageType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="imageType">
		<xs:attribute name="src" type="xs:string" use="required"/>
		<xs:attribute name="alt" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="width" type="xs:int"/>
		<xs:attribute name="height" type="xs:int"/>
		<xs:attribute name="align">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="bottom"/>
					<xs:enumeration value="middle"/>
					<xs:enumeration value="top"/>
					<xs:enumeration value="left"/>
					<xs:enumeration value="right"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="border" type="xs:int"/>
		<xs:attribute name="hspace" type="xs:int"/>
		<xs:attribute name="vspace" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="linkType">
		<xs:choice>
			<xs:element ref="image"/>
			<xs:element ref="text"/>
		</xs:choice>
		<xs:attribute name="href" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:NMTOKEN"/>
		<xs:attribute name="class" type="xs:string"/>
		<xs:attribute name="onMouseOver" type="xs:string"/>
		<xs:attribute name="onMouseOut" type="xs:string"/>
		<xs:attribute name="onclick" type="xs:string"/>
	</xs:complexType>
	<xs:element name="imageFlash">
		<xs:complexType>
			<xs:attribute name="movie" type="xs:string" use="required"/>
			<xs:attribute name="width" type="xs:string" use="required"/>
			<xs:attribute name="height" type="xs:string" use="required"/>
			<xs:attribute name="page" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="teaser-box">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element name="teaser" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="0"/>
							<xs:element ref="text" minOccurs="0"/>
							<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="titlebgcolor" type="xs:string" use="required"/>
			<xs:attribute name="bodybgcolor" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== zeluizgo/oprev/home.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 2 (http://www.xmlspy.com) by Jose Luiz (Modem Media) -->
<center-area xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="P:\odontoprev\portal\fontes\xml\global\website.xsd">
	<nlogado>
		<destaque bodybgcolor="#E7EEF3" titlebgcolor="#E7EEF3" height="60" width="209">
			<title>
				<text>CENTRAL DE INFORMAÇÕES</text>
			</title>
			<body>
				<text>Acompanhe seus tratamentos on-line.<br/>
					<image src="/img/fals_azul.gif" width="177" height="1" vspace="7" alt=""/>
					<br/>
					<b>
						<link href="/wrapper/vitrine.jsp?m=tratamento&amp;d=ass" class="linkpreto">
							<text>Clique aqui</text>
						</link>
					</b>
				</text>
			</body>
		</destaque>
		<destaque bodybgcolor="#E7EEF3" titlebgcolor="#E7EEF3" height="60" width="209">
			<title>
				<text>SERVIÇOS</text>
			</title>
			<body>
				<text>Encontre um dentista mais próximo de sua casa.<br/>
					<image src="/img/fals_azul.gif" width="177" height="1" vspace="7" alt=""/>
					<br/>
					<b>
						<link href="/wrapper/vitrine.jsp?m=rede&amp;d=ass" class="linkpreto">
							<text>Saiba mais</text>
						</link>
					</b>
				</text>
			</body>
		</destaque>
		<destaque bodybgcolor="#E7EEF3" titlebgcolor="#E7EEF3" height="50" width="420">
			<title>
				<text>NOVIDADES</text>
			</title>
			<body>
				<link href="/servico/novidades/news0104.jsp?d=ass" class="linkpreto">
					<text>
						22º CIOSP - Mais de 10 mil horas de treinamento para rede credenciada. <br/>
						<br/>
					</text>
				</link>
				<link href="/servico/novidades/news0104a.jsp?d=ass" class="linkpreto">
					<text>
							Atenas 2004 - OdontoPrev rumo à Atenas.
						</text>
				</link>
			</body>
		</destaque>
		<imageFlash movie="/flash/associados_01.swf" width="420" height="191" page="/tour/tour.jsp?d=ass&amp;flash=tourassociados.swf"/>
	</nlogado>
	<logado>
		<destaque bodybgcolor="#E7EEF3" titlebgcolor="#E7EEF3" height="1">
			<title>
				<text>FIQUE POR DENTRO</text>
			</title>
			<body>
				<text>Sua gengiva sangra? Você pode estar com a doença Periodontal.<br/>
					<br/>
					<b>
						<link href="/servico/novidades/news0803b.jsp?d=ass" class="linkpreto">
							<text>Saiba mais</text>
						</link>
					</b>
				</text>
			</body>
		</destaque>
		<destaque bodybgcolor="#E7EEF3" titlebgcolor="#E7EEF3" height="1">
			<title>
				<text>QUEREMOS SABER</text>
			</title>
			<body>
				<text>O que você achou do novo site da OdontoPrev?<br/>
					<br/>
					<b>
						<link href="/inst/faleconosco.do?contato=7" class="linkpreto">
							<text>Dê sua opinião.</text>
						</link>
					</b>
				</text>
			</body>
		</destaque>
		<teaser-box titlebgcolor="#929292" bodybgcolor="#C4C4C4">
			<title>
				<text>SUAS MENSAGENS</text>
			</title>
			<teaser>
				<text> Receba por e-mail o seu extrato de abertura de tratamento.</text>
				<link href="/servico/odontoprevmail/verOdontoprevMailAbertura.do" class="linkpreto">
					<text>
						<b>Clique aqui</b>
					</text>
				</link>
			</teaser>
			<teaser>
				<text> Consulte seu informativo de Imposta de Renda.</text>
				<link href="/servico/ir/verExtrato.do" class="linkpreto">
					<text>
						<b>Clique aqui.</b>
					</text>
				</link>
			</teaser>
		</teaser-box>
		<teaser-box titlebgcolor="#AFAFAF" bodybgcolor="#E0E0E0">
			<title>
				<text>ODONTOLOGIA &amp; PREVENÇÃO</text>
			</title>
			<teaser>
				<text>
					<b> Destaque do mês</b>
				</text>
				<link href="/servico/odontonews/opnews1003.jsp?d=ass" class="linkpreto">
					<text>Uma nova campanha e um portal diferenciado.</text>
				</link>
				<link href="/servico/odontonews/index.jsp?d=ass" class="linkpreto">
					<text>
						<b>Veja anteriores.</b>
					</text>
				</link>
			</teaser>
		</teaser-box>
		<teaser-box titlebgcolor="#AFAFAF" bodybgcolor="#E0E0E0">
			<title>
				<text>NOVIDADES</text>
			</title>
			<teaser>
				<link href="/servico/novidades/news0104.jsp" class="linkpreto">
					<text>01/2004 - 22º CIOSP - Mais de 10 mil horas de treinamento para rede credenciada. 
					
					</text>
				</link>
			</teaser>
			<teaser>
				<link href="/servico/novidades/news1103a.jsp" class="linkpreto">
					<text>01/2004 - Atenas 2004 - OdontoPrev rumo à Atenas.</text>
				</link>
			</teaser>
		</teaser-box>
	</logado>
</center-area>

=== zeluizgo/oprev/left-area.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Jose Luiz (Modem Media) -->
<left-area xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="P:\odontoprev\portal\fontes\xml\global\website.xsd">
	<menu userstatus="logged">
		<menu-section>
			<title>
				<text>SERVIÇOS</text>
			</title>
			<menu-folder id="pront">
				<title>
					<text>Prontuário Virtual</text>
				</title>
				<menu-subitem href="/servico/prontuario/verProntuario.do" class="linkbranco">
					<text>Extrato de Verificação</text>
				</menu-subitem>
				<menu-subitem href="/servico/tratamento/verTratamento.do" class="linkbranco">
					<text>Tratamentos</text>
				</menu-subitem>
				<menu-subitem href="/servico/ir/verExtrato.do" class="linkbranco">
					<text>Extrato</text>
				</menu-subitem>
				<menu-subitem href="/servico/ir/verExtratoSint.do" class="linkbranco">
					<text>Extrato Sintético</text>
				</menu-subitem>
			</menu-folder>
			<menu-folder id="reemb">
				<title>
					<text>Reembolso</text>
				</title>
				<menu-subitem href="/servico/reembolso/verReembolsoSolic.do" class="linkbranco">
					<text>Formulário Reembolso</text>
				</menu-subitem>
				<menu-subitem href="/servico/reembolso/verReembolso.do" class="linkbranco">
					<text>Formulários Utilizados</text>
				</menu-subitem>
				<menu-subitem href="#" class="linkbranco" onclick="window.open('/servico/reembolso/verReembolsoPend.do','reembolso','width=600,height=500,top=10,left=10,status=yes');">
					<text>Pendências Reembolso</text>
				</menu-subitem>
			</menu-folder>
			<menu-folder id="mail">
				<title>
					<text>OdontoPrev Mail</text>
				</title>
				<menu-subitem href="/servico/odontoprevmail/verOdontoprevMailAbertura.do" class="linkbranco">
					<text>Aviso de Abertura</text>
				</menu-subitem>
				<menu-subitem href="/servico/odontoprevmail/verOdontoprevMailExtrato.do" class="linkbranco">
					<text>Extrato de Tratamentos</text>
				</menu-subitem>
			</menu-folder>
			<menu-folder id="ir">
				<title>
					<text>Dedução de IR</text>
				</title>
				<menu-subitem href="/servico/ir/verExtrato.do" class="linkbranco">
					<text>Extrato</text>
				</menu-subitem>
				<menu-subitem href="/servico/ir/verExtratoSint.do" class="linkbranco">
					<text>Extrato Sintético</text>
				</menu-subitem>
			</menu-folder>
		</menu-section>
		<menu-section>
			<title>
				<text>CENTRAL DE ATENDIMENTO</text>
			</title>
			<menu-item href="/servico/indicacao/verIndicacao.do?d=ass" class="linkbranco">
				<text>Indicação de Dentista</text>
			</menu-item>
		</menu-section>
		<menu-section>
			<title>
				<text>CENTRAL DE INFORMAÇÕES</text>
			</title>
			<menu-item href="/servico/rede/verRede.do?d=ass" class="linkbranco">
				<text>Rede Credenciada</text>
			</menu-item>
			<menu-item href="/servico/etica/verEticaAssociado.do?d=ass" class="linkbranco">
				<text>Código de Ética</text>
			</menu-item>
			<menu-item href="/servico/odontonews/index.jsp?d=ass" class="linkbranco">
				<text>Odontologia &amp; Prevenção</text>
			</menu-item>
			<menu-item href="/servico/novidades/novidades.jsp" class="linkbranco">
				<text>Novidades</text>
			</menu-item>
		</menu-section>
	</menu>
	<menu userstatus="notlogged">
		<menu-section>
			<title>
				<text>SERVIÇOS</text>
			</title>
			<menu-item href="/wrapper/vitrine.jsp?m=tratamento&amp;d=ass" class="linkbranco">
				<text>Prontuário Virtual</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=reembolso&amp;d=ass" class="linkbranco">
				<text>Reembolso</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=suaconta&amp;d=ass" class="linkbranco">
				<text>Sua Conta</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=agenda&amp;d=ass" class="linkbranco">
				<text>Agenda Eletrônica</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=previa&amp;d=ass" class="linkbranco">
				<text>Prévia de Reembolso</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=status&amp;d=ass" class="linkbranco">
				<text>Status de Reembolso</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=managed&amp;d=ass" class="linkbranco">
				<text>Managed Care Ativo</text>
			</menu-item>
		</menu-section>
		<menu-section>
			<title>
				<text>CENTRAL DE ATENDIMENTO</text>
			</title>
			<menu-item href="/wrapper/vitrine.jsp?m=indicacao&amp;d=ass" class="linkbranco">
				<text>Indicação de Dentista</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=manuais&amp;d=ass" class="linkbranco">
				<text>Manuais</text>
			</menu-item>
		</menu-section>
		<menu-section>
			<title>
				<text>CENTRAL DE INFORMAÇÕES</text>
			</title>
			<menu-item href="/wrapper/vitrine.jsp?m=relacao&amp;d=ass" class="linkbranco">
				<text>Relação de Associados</text>
			</menu-item>
			<menu-item href="/wrapper/vitrine.jsp?m=rede&amp;d=ass" class="linkbranco">
				<text>Rede Credenciada</text>
			</menu-item>
		</menu-section>
	</menu>
</left-area>
